"""
env.py  --  The Delivery Robot world (a tabular Markov Decision Process).

Week 2 assignment for the Introduction to Reinforcement Learning course.
By the Electronics & Robotics Club, BITS Goa.

You do NOT edit this file. It builds the world your robot lives in and hands your
Dynamic Programming code (in dp.py) everything it needs: the list of states, the
list of actions, which states are terminal, and, for any state and action, the
full list of possible outcomes with their probabilities and rewards.

The world is a grid described by a small ASCII map:

    #  wall / shelf     the robot can never stand here; walking into it wastes a
                        move and the robot stays put
    .  free floor       a normal tile, free to enter (`step_cost`, default 0)
    R  rough tile       slow and costly, costs `rough_cost` (default -3) to enter
    ~  slippery tile     entering is free, but see "slip" below
    S  start / depot     where the robot begins
    G  goal / door       the customer's door. Delivering here ends the episode with
                        a big `goal_reward` (default +100)
    H  hazard            stairs or a loading pit. Falling in ends the episode with a
                        big negative `hazard_reward` (default -60)
    P  package pickup     (Level 3 only) the robot must collect the package here
                        before a delivery at G counts

Rewards are earned on the *transition*: the reward is decided by the tile the robot
lands on. Plain floor is free, so the only push to hurry is the discount gamma: the
sooner the robot reaches the door, the more the +100 is worth. The optimal policy is
therefore the shortest safe route, steering around rough tiles and the hazard.

Every idea from the notes maps straight onto three methods below:
    env.states                list of integer state ids, 0 .. n_states-1
    env.actions               ["up", "down", "left", "right"]
    env.is_terminal(s)        True for a delivered goal or a hazard
    env.transitions(s, a)     list of (probability, next_state, reward) triples

Because your dp.py only ever calls env.transitions(...), the very same code solves
the deterministic map, the slippery map, and the pickup map with no changes. A model
gives the algorithm the outcomes and their probabilities; it does not need to know how
the world produced them.
"""

from __future__ import annotations

from typing import Dict, List, Tuple

# Actions and the (row, column) change each one makes.
ACTION_DELTAS: Dict[str, Tuple[int, int]] = {
    "up": (-1, 0),
    "down": (1, 0),
    "left": (0, -1),
    "right": (0, 1),
}
ACTIONS: List[str] = list(ACTION_DELTAS)

# When the robot slips, it slides to one of the two sideways directions.
PERPENDICULAR: Dict[str, Tuple[str, str]] = {
    "up": ("left", "right"),
    "down": ("left", "right"),
    "left": ("up", "down"),
    "right": ("up", "down"),
}


class GridWorld:
    """A tabular MDP built from an ASCII map.

    Parameters
    ----------
    layout : str
        The ASCII map (see the module docstring for the tile characters).
    gamma : float
        The discount factor for this world. Stored for convenience; the dp.py
        functions still take gamma as an argument so you can experiment with it.
    slip : float
        The slip probability p. On a slippery tile the robot moves in the
        intended direction with probability 1 - 2p, and sideways (each way) with
        probability p. On a non-slippery tile the move is deterministic.
    global_slip : bool
        If True, every tile is slippery (an ice rink). If False, only tiles drawn
        as '~' are slippery.
    step_cost, rough_cost, goal_reward, hazard_reward : float
        The reward earned for entering a free tile, a rough tile, the goal, and a
        hazard, respectively.
    has_package_dim : bool
        If True (Level 3), the state also tracks whether the robot is carrying the
        package. A delivery at G only ends the episode once the package is held.
    """

    def __init__(
        self,
        layout: str,
        gamma: float = 0.95,
        slip: float = 0.0,
        global_slip: bool = False,
        step_cost: float = 0.0,
        rough_cost: float = -3.0,
        goal_reward: float = 100.0,
        hazard_reward: float = -60.0,
        has_package_dim: bool = False,
    ) -> None:
        self.grid = [list(row) for row in layout.strip("\n").splitlines()]
        self.n_rows = len(self.grid)
        self.n_cols = max(len(row) for row in self.grid)
        # Pad short rows with walls so the grid is a clean rectangle.
        for row in self.grid:
            row += ["#"] * (self.n_cols - len(row))

        self.gamma = gamma
        self.slip = slip
        self.global_slip = global_slip
        self.step_cost = step_cost
        self.rough_cost = rough_cost
        self.goal_reward = goal_reward
        self.hazard_reward = hazard_reward
        self.has_package_dim = has_package_dim

        self.actions = ACTIONS

        # Locate the special tiles.
        self._start_rc = None
        self._goal_rc = None
        self._pickup_rc = None
        for r in range(self.n_rows):
            for c in range(self.n_cols):
                t = self.grid[r][c]
                if t == "S":
                    self._start_rc = (r, c)
                elif t == "G":
                    self._goal_rc = (r, c)
                elif t == "P":
                    self._pickup_rc = (r, c)
        if self._start_rc is None:
            raise ValueError("The map has no start tile 'S'.")
        if self._goal_rc is None:
            raise ValueError("The map has no goal tile 'G'.")
        if self.has_package_dim and self._pickup_rc is None:
            raise ValueError("A pickup map needs a 'P' tile.")

        self._ncells = self.n_rows * self.n_cols
        self._n_pkg = 2 if self.has_package_dim else 1
        self.n_states = self._ncells * self._n_pkg
        self.states = list(range(self.n_states))

        start_hp = 0  # the robot starts without the package
        self.start_state = self.encode(self._start_rc[0], self._start_rc[1], start_hp)

        # Precompute the whole model once (state, action) -> outcomes. This is an
        # internal speed-up only; your dp.py still just calls env.transitions(...).
        self._model: Dict[Tuple[int, str], List[Tuple[float, int, float]]] = {}
        for s in self.states:
            for a in self.actions:
                self._model[(s, a)] = self._compute_transitions(s, a)

    # ------------------------------------------------------------------ layout
    def tile(self, r: int, c: int) -> str:
        return self.grid[r][c]

    def is_wall(self, r: int, c: int) -> bool:
        return self.grid[r][c] == "#"

    def in_bounds(self, r: int, c: int) -> bool:
        return 0 <= r < self.n_rows and 0 <= c < self.n_cols

    def _is_slippery(self, r: int, c: int) -> bool:
        if self.slip <= 0.0:
            return False
        return self.global_slip or self.grid[r][c] == "~"

    # --------------------------------------------------------- state encoding
    def encode(self, r: int, c: int, hp: int = 0) -> int:
        """Turn (row, column, has_package) into a single integer state id."""
        return (r * self.n_cols + c) + hp * self._ncells

    def decode(self, s: int) -> Tuple[int, int, int]:
        """Turn a state id back into (row, column, has_package)."""
        hp, cell = divmod(s, self._ncells)
        r, c = divmod(cell, self.n_cols)
        return r, c, hp

    # ------------------------------------------------------------- terminals
    def is_terminal(self, s: int) -> bool:
        """A state is terminal once the robot has fallen in a hazard, or has
        delivered the package at the goal."""
        r, c, hp = self.decode(s)
        if self.tile(r, c) == "H":
            return True
        if self.tile(r, c) == "G":
            # Without the package dimension every visit to G ends the episode.
            # With it, the delivery only counts while carrying the package.
            return (not self.has_package_dim) or hp == 1
        return False

    # ------------------------------------------------------- reward on arrival
    def _reward_for_entering(self, r: int, c: int, hp_after: int) -> float:
        t = self.tile(r, c)
        if t == "H":
            return self.hazard_reward
        if t == "G" and ((not self.has_package_dim) or hp_after == 1):
            return self.goal_reward
        if t == "R":
            return self.rough_cost
        return self.step_cost

    # ----------------------------------------------------------- the model
    def transitions(self, s: int, a: str) -> List[Tuple[float, int, float]]:
        """Return every possible outcome of taking action `a` in state `s`, as a
        list of (probability, next_state, reward) triples. The probabilities sum
        to 1.

        Terminal states self-loop with reward 0, so their value is 0 no matter
        what. In your dp.py you should skip terminal states (their value stays 0),
        exactly as the notes do.
        """
        return self._model[(s, a)]

    def _compute_transitions(self, s: int, a: str) -> List[Tuple[float, int, float]]:
        if self.is_terminal(s):
            return [(1.0, s, 0.0)]

        r, c, hp = self.decode(s)

        if self._is_slippery(r, c):
            p = self.slip
            left_a, right_a = PERPENDICULAR[a]
            moves = [(a, 1.0 - 2.0 * p), (left_a, p), (right_a, p)]
        else:
            moves = [(a, 1.0)]

        # Accumulate outcomes, merging any that land in the same place.
        merged: Dict[Tuple[int, float], float] = {}
        for direction, prob in moves:
            if prob <= 0.0:
                continue
            nr, nc, nhp, reward = self._apply(r, c, hp, direction)
            key = (self.encode(nr, nc, nhp), reward)
            merged[key] = merged.get(key, 0.0) + prob

        return [(prob, s2, reward) for (s2, reward), prob in merged.items()]

    def _apply(self, r: int, c: int, hp: int, direction: str):
        """Move one step in `direction` from (r, c). Walls and edges bounce the
        robot back to (r, c). Returns (row, col, has_package_after, reward)."""
        dr, dc = ACTION_DELTAS[direction]
        nr, nc = r + dr, c + dc
        if not self.in_bounds(nr, nc) or self.is_wall(nr, nc):
            nr, nc = r, c  # bumped a wall or the edge: stay put

        nhp = hp
        if self.has_package_dim and self.tile(nr, nc) == "P":
            nhp = 1  # picked up the package

        reward = self._reward_for_entering(nr, nc, nhp)
        return nr, nc, nhp, reward


# ---------------------------------------------------------------------------
#  Small policy helpers, so dp.py and the checker speak the same language.
#  A policy maps every non-terminal state to a distribution over actions:
#      policy[s] = {"up": 0.25, "down": 0.25, "left": 0.25, "right": 0.25}
#  A deterministic policy just puts probability 1.0 on a single action.
# ---------------------------------------------------------------------------

def uniform_random_policy(env: GridWorld) -> Dict[int, Dict[str, float]]:
    """The 'wander aimlessly' policy: every action equally likely everywhere."""
    p = 1.0 / len(env.actions)
    return {
        s: {a: p for a in env.actions}
        for s in env.states
        if not env.is_terminal(s)
    }


def deterministic(action_of_state: Dict[int, str]) -> Dict[int, Dict[str, float]]:
    """Wrap a plain {state: action} choice into the {state: {action: prob}}
    form the evaluation code expects."""
    return {s: {a: 1.0} for s, a in action_of_state.items()}


if __name__ == "__main__":
    # A quick self-test so you can confirm the file loads: python env.py
    demo = GridWorld("#####\n#S.G#\n#.#.#\n#..H#\n#####")
    print("states     :", demo.n_states)
    print("actions    :", demo.actions)
    print("start state:", demo.start_state, "->", demo.decode(demo.start_state))
    s = demo.start_state
    print("transitions from start, action 'right':")
    for prob, s2, reward in demo.transitions(s, "right"):
        print("   p={:.2f} -> {} reward={}".format(prob, demo.decode(s2), reward))
    total = sum(p for p, _, _ in demo.transitions(s, "right"))
    assert abs(total - 1.0) < 1e-9, "transition probabilities must sum to 1"
    print("OK: env loads and probabilities sum to 1.")
