"""
maps.py  --  The Delivery Robot maps, as ASCII strings.

You do NOT edit this file (except to design your own map, see the bottom). Each map is
a warehouse for your robot. The tile characters are explained in env.py:

    #  wall      .  free floor    R  rough tile    ~  slippery tile
    S  start     G  goal / door   H  hazard        P  package pickup

The levels build on each other, and grow much larger:

    LEVEL 1  a small deterministic warehouse, where you first test that your four
             functions are correct.
    LEVEL 2  a medium maze whose whole floor is slippery, so moves sometimes slide
             sideways.
    LEVEL 3  a large maze (over 2000 states) with hazards, rough patches, and a large
             slippery region. The robot must collect the package at P, then deliver it
             at G.

There is also a big GRAND map you can solve for extra practice.

The larger maps were generated with make_maps.py (a mentor tool): a maze is carved,
then every dead end is opened into the corridor beside it, so the whole warehouse is a
connected network of loops with no wasted stubs. The start, pickup, and door sit far
apart, and hazards block the obvious routes so the best path has to wind around them.
"""

# ------------------------------------------------------------------- Level 1
# Small and deterministic: the sanity check for your four functions.
LEVEL1 = """
########
#S.....#
#.####.#
#.#R...#
#.#.##H#
#....G.#
########
"""

# ------------------------------------------------------------------- Level 2
# A medium maze. The whole floor is slippery (global slip, set in the config
# below), so every move can slide sideways.
LEVEL2 = """
#################
#S....#.........#
#.###.#.#.#.#.#.#
#...#..H#.#.#...#
#.#.###.#.#.###.#
#.#.......#...#.#
#.#########.#.#.#
#...#.....#.#.#.#
#.#.#.#R#.#.#.#.#
#.....#RR..H#H.G#
#################
"""

# ------------------------------------------------------------------- Level 3
# A huge maze (31x41, ~2500 states) with a pickup. Collect the package at P, then
# deliver at G, past dozens of hazards, many rough tiles, and a big slippery region.
LEVEL3 = """
#########################################
#S.H#.....#.......#.....#...............#
#.#.#.#.#.#.#.###.#.###.#R#####H#####.#.#
#.#.....#.#.#...#.#.....#.........#..H..#
#.#######.#R###.#.#.#.#####.#####.#.###.#
#...HR#...#...#..R#.#.....#.#.H...#.....#
#.###.#.#.#H#.#.###.#####.#.#.#.###R#####
#...#...#H..#.#.........#...#.#R#H..#...#
#.#.#########R#########.#####.#.#.###.#.#
#.#.#....R..#.#.H.HHH.....HRH.#H#P....#.#
#.#.#.###.#.#.#.#########.#####.#######.#
#.#.#.H...#.#.#H..#.......#.............#
#.#.#.#####R#.#H#.#.#.#####.###.#####.###
#.#...#...#...#.#...#..H#.H...#.........#
#.#####.#.#####.#####.#.#.###.#########.#
#..HH...........#.....#.#R#.............#
#.#.###.#########.#####.#.#.###########.#
#.#.#.........#......~#~~~#~~~#~~~~~~~#~#
#.#.#.#####.#.#.#####~#####~#~#~#~###~#~#
#.#......R..#........~~~~~#~~~#~#~~~#~#~#
#.###################~#~#~###~#H###~#~#~#
#..H...H#...#..R....#H#R#~~~~~#~~~#~~~~~#
#####.#.#.#.#.###.#.#H#~#######~#~#######
#.....#.....#.#...#..~#~RR~~R~#R#~#~~~~~#
#.#########.#.#.#############~#~#~#~###~#
#...........#.#......~~~~~~R#~~~#~#~#~~~#
#.#####.#####.#############~###~#~#~#~###
#.....#.......#......~#~~G#~~~~~#~~R#~~~#
#.###.#########.#####~#~#~#~###~#######~#
#...................H~~~~~#R~~~R~~~~~~~~#
#########################################
"""

# ------------------------------------------------------------- Grand Warehouse
# An optional, bigger map with a package to fetch. Solve it for extra practice, or
# edit it (or write your own) to see how your solver copes with a larger world.
GRAND = """
###############################
#S.HHH........#....H..#......H#
#.#.#.#######.#.#.###.#R###.#.#
#G..#.#..H.H#.#.....#.#R..#...#
#.###.#.###.#.#.###.#.#.#.#.#.#
#...#.....#.....#.....#.....#.#
###.#.###.#.#####.#####.#####.#
#...#H....#.H...#..~~~~R#~~~~~#
#.###.###.#####.#########R###~#
#.#...#.H.#...#.#..~~R~~#~R~#~#
#.#.#.#.###.#.#.#.#####~###~#~#
#...#.#.#R..#.#...#~~~#R#~~~~~#
###.#.#.#.###.#####~#~#~#~#####
#..H#...#...#.#....~#~~~#~~~~~#
#.#.#.###.#.#.#.###~#~###~###~#
#.#.....#...#.....#~~~~~~~~~#P#
#.#####.###.#.###.#########~#~#
#.....#...#.#...H..~#~~H#~~~~~#
#.#.#.#.#.#.###.#H#.#.#.#.###.#
#.......#.....H.#.....#.......#
###############################
"""


# Each config gives the map plus the world settings the graders and the driver
# use. gamma is the discount factor; slip is the slip probability. The reward
# numbers (free floor, rough -3, goal +100, hazard -60) come from env.GridWorld.
# The bigger the maze, the closer gamma is to 1, so the goal reward still reaches
# across the whole warehouse.
CONFIGS = {
    "level1": dict(
        layout=LEVEL1,
        gamma=0.95,
        slip=0.0,
        global_slip=False,
        has_package_dim=False,
        title="Level 1: The Basic Delivery (deterministic)",
    ),
    "level2": dict(
        layout=LEVEL2,
        gamma=0.97,
        slip=0.12,
        global_slip=True,
        has_package_dim=False,
        title="Level 2: The Slippery Floor (stochastic)",
    ),
    "level3": dict(
        layout=LEVEL3,
        gamma=0.997,
        slip=0.08,
        global_slip=False,
        has_package_dim=True,
        title="Level 3: The Full Depot Run (pickup then deliver)",
    ),
    "grand": dict(
        layout=GRAND,
        gamma=0.995,
        slip=0.08,
        global_slip=False,
        has_package_dim=True,
        title="The Grand Warehouse (optional extra practice)",
    ),
}

# The slip probabilities used for the "how cautious does the policy get?" figure.
SLIP_SWEEP = [0.0, 0.05, 0.15, 0.25]
