"""
plotting.py  --  All the pictures for the Delivery Robot assignment.

You do NOT edit this file, and you never have to write plotting code: run.py calls
these functions for you after your dp.py computes the values and policies. Every
figure is saved to the figures/ folder as a PNG (and the rollout as an MP4 video).

Everything here uses the "Agg" backend, which draws straight to a file and needs no
screen. That is what lets it run identically on a plain Ubuntu terminal and inside
WSL, where there is no display by default.
"""

from __future__ import annotations

import matplotlib
matplotlib.use("Agg")  # draw to files, no screen needed (works on WSL)

from pathlib import Path
from typing import Dict, List, Optional

import math

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap, TwoSlopeNorm
from matplotlib.patches import Rectangle, Circle, Polygon, FancyBboxPatch

# Figures go in <project root>/figures. When this file is shipped inside the
# provided "utils" folder, the project root is one level up (next to dp.py).
_HERE = Path(__file__).resolve().parent
_ROOT = _HERE.parent if _HERE.name == "utils" else _HERE
FIGDIR = _ROOT / "figures"
FIGDIR.mkdir(exist_ok=True)

# The course palette (colorblind-safe: blue vs orange is the main contrast).
PALETTE = {
    "blue": "#1b4965", "orange": "#e8820c", "teal": "#0891b2",
    "purple": "#7c3aed", "vermillion": "#d55e00", "slate": "#475569",
    "ink": "#0f172a", "accent": "#0E2F4F", "good": "#0891b2", "bad": "#d55e00",
}
# Value colormap: warm orange for low/negative, white at zero, blue for high.
VALUE_CMAP = LinearSegmentedColormap.from_list(
    "delivery", [PALETTE["orange"], "#fbe7cf", "#ffffff", "#cfe3f3", PALETTE["blue"]])

ARROW = {"up": (0, -1), "down": (0, 1), "left": (-1, 0), "right": (1, 0)}
GOLD, PARCEL, PARCEL_EDGE, BODY = "#f2b705", "#c8925a", "#6b3f1d", "#5b7fa6"


# ---------------------------------------------------------------------------
#  Little game-style icons, drawn with plain shapes so they render identically
#  on every machine (no emoji fonts needed). Cell (r, c) is one unit wide.
# ---------------------------------------------------------------------------
def _star_pts(cx, cy, ro=0.30, ri=0.13, n=5, rot=90.0):
    pts = []
    for i in range(2 * n):
        ang = math.radians(rot + i * 180.0 / n)
        rr = ro if i % 2 == 0 else ri
        pts.append((cx + rr * math.cos(ang), cy - rr * math.sin(ang)))
    return pts


def _icon(ax, cy, cx, kind):
    """Draw a game icon centred on grid cell (row cy, col cx)."""
    ink = PALETTE["ink"]
    z = 5
    if kind == "robot":
        ax.add_patch(FancyBboxPatch((cx - 0.22, cy - 0.14), 0.44, 0.30,
                     boxstyle="round,pad=0.02,rounding_size=0.08",
                     facecolor=BODY, edgecolor=ink, lw=1.4, zorder=z))
        ax.add_patch(Rectangle((cx - 0.22, cy + 0.15), 0.44, 0.05,
                     facecolor=ink, zorder=z))
        for ex in (-0.095, 0.095):
            ax.add_patch(Circle((cx + ex, cy), 0.055, facecolor="white",
                         edgecolor=ink, lw=0.8, zorder=z + 1))
            ax.add_patch(Circle((cx + ex, cy), 0.022, facecolor=ink, zorder=z + 2))
        ax.plot([cx, cx], [cy - 0.14, cy - 0.30], color=ink, lw=1.4, zorder=z)
        ax.add_patch(Circle((cx, cy - 0.32), 0.04, facecolor=PALETTE["vermillion"],
                     edgecolor=ink, lw=0.6, zorder=z + 1))
    elif kind == "goal":
        ax.add_patch(Polygon(_star_pts(cx, cy), closed=True, facecolor=GOLD,
                     edgecolor=ink, lw=1.3, zorder=z, joinstyle="round"))
    elif kind == "hazard":
        ax.add_patch(Polygon([(cx, cy - 0.28), (cx - 0.30, cy + 0.24),
                     (cx + 0.30, cy + 0.24)], closed=True, facecolor=PALETTE["orange"],
                     edgecolor=ink, lw=1.6, zorder=z, joinstyle="round"))
        ax.plot([cx, cx], [cy - 0.08, cy + 0.10], color=ink, lw=2.6, zorder=z + 1,
                solid_capstyle="round")
        ax.add_patch(Circle((cx, cy + 0.17), 0.028, facecolor=ink, zorder=z + 1))
    elif kind == "parcel":
        ax.add_patch(Rectangle((cx - 0.24, cy - 0.22), 0.48, 0.44, facecolor=PARCEL,
                     edgecolor=PARCEL_EDGE, lw=1.6, zorder=z))
        ax.plot([cx, cx], [cy - 0.22, cy + 0.22], color=PARCEL_EDGE, lw=1.6, zorder=z + 1)
        ax.plot([cx - 0.24, cx + 0.24], [cy, cy], color=PARCEL_EDGE, lw=1.6, zorder=z + 1)
    elif kind == "depot":  # the home base (a little warehouse)
        ax.add_patch(Polygon([(cx - 0.30, cy - 0.02), (cx + 0.30, cy - 0.02),
                     (cx, cy - 0.30)], closed=True, facecolor="#8a5a3b",
                     edgecolor=ink, lw=1.3, zorder=z, joinstyle="round"))
        ax.add_patch(Rectangle((cx - 0.22, cy - 0.02), 0.44, 0.26, facecolor="#d9c6a5",
                     edgecolor=ink, lw=1.3, zorder=z))
        ax.add_patch(Rectangle((cx - 0.06, cy + 0.06), 0.12, 0.18,
                     facecolor="#6b3f1d", zorder=z + 1))


def _rough_dots(ax, cy, cx):
    for dx, dy in [(-0.12, 0.10), (0.11, -0.05), (0.02, 0.17), (-0.05, -0.14)]:
        ax.add_patch(Circle((cx + dx, cy + dy), 0.035, facecolor="#7a6a4a",
                     edgecolor="none", zorder=2))


def _slip_wave(ax, cy, cx):
    xs = np.linspace(cx - 0.30, cx + 0.30, 24)
    ys = cy + 0.16 * np.sin((xs - cx) / 0.30 * math.pi * 1.5)
    ax.plot(xs, ys, color=PALETTE["teal"], lw=1.6, zorder=2, solid_capstyle="round")


def set_style():
    plt.rcParams.update({
        "figure.dpi": 130, "savefig.dpi": 200,
        "axes.grid": True, "grid.alpha": 0.25, "grid.linestyle": "--",
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.titlesize": 13, "axes.titleweight": "bold", "axes.labelsize": 11,
        "font.size": 11, "legend.frameon": False,
    })


def _save(fig, name):
    path = FIGDIR / name
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print("wrote", path)
    return path


# ---------------------------------------------------------------------------
#  The map: value heatmap with the policy arrows on top.
# ---------------------------------------------------------------------------
def _value_grid(env, V, hp):
    """Reshape V (for one has_package layer) into a (rows, cols) array; walls NaN."""
    grid = np.full((env.n_rows, env.n_cols), np.nan)
    for r in range(env.n_rows):
        for c in range(env.n_cols):
            if not env.is_wall(r, c):
                grid[r, c] = V[env.encode(r, c, hp)]
    return grid


def _draw_layer(ax, env, V, policy, hp, title, show_values=True):
    grid = _value_grid(env, V, hp)
    finite = grid[np.isfinite(grid)]
    lo, hi = float(np.min(finite)), float(np.max(finite))
    norm = TwoSlopeNorm(vmin=min(lo, -0.1), vcenter=0.0, vmax=max(hi, 0.1))
    show_text = show_values and env.n_rows * env.n_cols <= 90

    masked = np.ma.masked_invalid(grid)
    cmap = VALUE_CMAP.copy()
    cmap.set_bad(PALETTE["slate"])  # walls
    ax.imshow(masked, cmap=cmap, norm=norm, origin="upper")

    icon_of = {"S": "depot", "G": "goal", "H": "hazard", "P": "parcel"}
    for r in range(env.n_rows):
        for c in range(env.n_cols):
            t = env.tile(r, c)
            if t == "#":
                continue
            s = env.encode(r, c, hp)
            # a faint tile-colour wash for the goal (gold) and hazard (orange)
            if t == "G":
                ax.add_patch(Rectangle((c - 0.5, r - 0.5), 1, 1, facecolor=GOLD,
                             alpha=0.18, zorder=1))
            elif t == "H":
                ax.add_patch(Rectangle((c - 0.5, r - 0.5), 1, 1,
                             facecolor=PALETTE["orange"], alpha=0.18, zorder=1))
            elif t == "R":
                _rough_dots(ax, r, c)
            elif t == "~":
                _slip_wave(ax, r, c)

            special = t in icon_of
            if special:
                _icon(ax, r, c, icon_of[t])
            else:
                # policy arrow on ordinary floor (skip terminals)
                if policy is not None and s in policy and not env.is_terminal(s):
                    a = max(policy[s], key=policy[s].get)
                    dx, dy = ARROW[a]
                    ax.arrow(c, r - 0.05, dx * 0.30, dy * 0.30, head_width=0.22,
                             head_length=0.20, lw=2.4, fc=PALETTE["vermillion"],
                             ec=PALETTE["vermillion"], length_includes_head=True,
                             zorder=3)
                if show_text and not env.is_terminal(s):
                    ax.text(c, r + 0.34, f"{grid[r, c]:.0f}", ha="center", va="center",
                            fontsize=10, color=PALETTE["ink"], zorder=3)
    ax.set_xticks([]); ax.set_yticks([]); ax.grid(False)
    ax.set_title(title, fontsize=14, fontweight="bold")


def figure_value_policy(env, V, policy, name, title=""):
    """Value heatmap + greedy arrows. Two panels if the world tracks the package."""
    if env.has_package_dim:
        fig, axes = plt.subplots(1, 2, figsize=(2.0 + 1.05 * env.n_cols * 2, 1.4 + 0.95 * env.n_rows))
        _draw_layer(axes[0], env, V, policy, 0, "before pickup (no package)")
        _draw_layer(axes[1], env, V, policy, 1, "after pickup (carrying package)")
        fig.suptitle(title, fontsize=13, fontweight="bold", y=1.04)
    else:
        fig, ax = plt.subplots(figsize=(1.6 + 1.05 * env.n_cols, 1.2 + 0.95 * env.n_rows))
        _draw_layer(ax, env, V, policy, 0, title)
    return _save(fig, name)


def figure_world(env, name, title="The warehouse"):
    """Just the map, no values, for the assignment PDF and the README."""
    fig, ax = plt.subplots(figsize=(1.6 + 1.05 * env.n_cols, 1.2 + 0.95 * env.n_rows))
    _draw_layer(ax, env, np.zeros(env.n_states), None, 0, title, show_values=False)
    return _save(fig, name)


# ---------------------------------------------------------------------------
#  PI vs VI convergence race (sup-norm error to V* vs Bellman sweeps).
# ---------------------------------------------------------------------------
def figure_pi_vs_vi(vi_err, pi_x, pi_err, name="pi_vs_vi.png"):
    fig, ax = plt.subplots(figsize=(8.4, 4.4))
    ax.semilogy(np.arange(1, len(vi_err) + 1), vi_err, "o-", color=PALETTE["blue"],
                ms=3, lw=1.4, label="value iteration (1 sweep per step)")
    ax.semilogy(pi_x, pi_err, "s-", color=PALETTE["orange"], ms=7, lw=1.4,
                mfc="none", label="policy iteration (full evaluation per step)")
    ax.set_xlabel("cumulative Bellman sweeps over the state space")
    ax.set_ylabel(r"max error to $V_*$ (log scale)")
    ax.set_title("Policy iteration takes a few expensive steps; value iteration many cheap ones")
    ax.legend()
    return _save(fig, name)


# ---------------------------------------------------------------------------
#  Async: how fast the greedy POLICY becomes optimal (in-place vs two-array).
# ---------------------------------------------------------------------------
def figure_async_policy(curves, name="async_policy.png"):
    """curves: list of (label, color, wrong_counts_per_sweep)."""
    fig, ax = plt.subplots(figsize=(8.4, 4.4))
    for label, color, ys in curves:
        ax.plot(np.arange(1, len(ys) + 1), ys, "o-", color=PALETTE[color],
                ms=3, lw=1.6, label=label)
    ax.set_xlabel("sweeps")
    ax.set_ylabel("states whose greedy action is still wrong")
    ax.set_title("In-place updates settle the optimal policy sooner, and sweep order matters")
    ax.set_xlim(left=1)
    ax.legend()
    return _save(fig, name)


# ---------------------------------------------------------------------------
#  Modified policy iteration: the k dial between VI and PI.
# ---------------------------------------------------------------------------
def figure_modified_pi(curves, name="modified_pi.png"):
    """curves: list of (label, color, backups, errors)."""
    fig, ax = plt.subplots(figsize=(8.4, 4.4))
    for label, color, backups, errs in curves:
        ax.semilogy(backups, errs, "o-", color=PALETTE[color], ms=4, lw=1.4, label=label)
    ax.set_xlabel("cumulative evaluation sweeps")
    ax.set_ylabel(r"max error to $V_*$ (log scale)")
    ax.set_title(r"Modified policy iteration: $k=1$ is value iteration, large $k$ is policy iteration")
    ax.legend()
    return _save(fig, name)


# ---------------------------------------------------------------------------
#  Policy vs slip probability: how cautious does the robot get?
# ---------------------------------------------------------------------------
def figure_slip_panel(envs_Vs_pols_titles, name="slip_panel.png"):
    items = envs_Vs_pols_titles
    n = len(items)
    env0 = items[0][0]
    fig, axes = plt.subplots(1, n, figsize=(1.2 + 1.0 * env0.n_cols * n, 1.4 + 0.9 * env0.n_rows))
    if n == 1:
        axes = [axes]
    for ax, (env, V, pol, title) in zip(axes, items):
        _draw_layer(ax, env, V, pol, 0, title)
    fig.suptitle("The optimal route bends away from the hazard as the floor gets more slippery",
                 fontsize=13, fontweight="bold", y=1.06)
    return _save(fig, name)


# ---------------------------------------------------------------------------
#  Curse of dimensionality: solve time vs number of states.
# ---------------------------------------------------------------------------
def figure_curse(state_counts, times, labels, name="curse.png"):
    fig, ax = plt.subplots(figsize=(8.0, 4.4))
    ax.plot(state_counts, times, "o-", color=PALETTE["purple"], ms=7, lw=1.6)
    for x, y, lab in zip(state_counts, times, labels):
        ax.annotate(lab, (x, y), textcoords="offset points", xytext=(6, 6),
                    fontsize=9, color=PALETTE["slate"])
    ax.set_xlabel("number of states in the table")
    ax.set_ylabel("time to solve (seconds)")
    ax.set_title("The curse of dimensionality: adding one dimension multiplies the work")
    return _save(fig, name)


# ---------------------------------------------------------------------------
#  The rollout: animate the robot following its optimal policy (MP4, headless).
# ---------------------------------------------------------------------------
def _q_value(env, V, s, a, gamma):
    return sum(p * (r + gamma * V[s2]) for p, s2, r in env.transitions(s, a))


def rollout(env, policy, seed=0, max_steps=400):
    """Follow the greedy policy from the start; return the list of visited states."""
    return [t["s"] for t in rollout_trace(env, None, policy, 0.0, seed, max_steps)]


def rollout_trace(env, V, policy, gamma, seed=0, max_steps=400):
    """Play one episode under the policy and record, at every step, the information
    a student needs to understand and debug the run: the value of the current cell,
    the action value q(s, a) of each of the four moves, which move the policy took,
    which move actually has the highest q, the reward, the running return, and
    whether the floor made the robot slip."""
    rng = np.random.default_rng(seed)
    s = env.start_state
    ret, disc, trace = 0.0, 1.0, []
    for _ in range(max_steps):
        r, c, hp = env.decode(s)
        if env.is_terminal(s):
            trace.append(dict(s=s, r=r, c=c, hp=hp, term=True, Vs=0.0, qs={},
                              action=None, best=None, reward=None, ret=ret, slipped=False))
            break
        a = max(policy[s], key=policy[s].get)
        qs = ({aa: _q_value(env, V, s, aa, gamma) for aa in env.actions}
              if V is not None else {})
        best = max(qs, key=qs.get) if qs else a
        outs = env.transitions(s, a)
        intended = max(outs, key=lambda o: o[0])[1]
        j = rng.choice(len(outs), p=[p for p, _, _ in outs])
        _, s2, rew = outs[j]
        slipped = len(outs) > 1 and s2 != intended
        ret += disc * rew
        trace.append(dict(s=s, r=r, c=c, hp=hp, term=False,
                          Vs=(float(V[s]) if V is not None else 0.0), qs=qs,
                          action=a, best=best, reward=rew, ret=ret, slipped=slipped))
        disc *= gamma
        s = s2
    return trace


def _panel_legend(axp):
    """Static key of the symbols, drawn once on the info panel."""
    axp.text(0.5, 0.985, "What the robot sees", ha="center", va="top",
             fontsize=13, fontweight="bold", color=PALETTE["accent"])
    axp.text(0.04, 0.235, "symbols", fontsize=9.5, fontweight="bold",
             color=PALETTE["slate"])
    items = [("house", "start / depot"), ("star", "goal / door"),
             ("triangle", "hazard (ends run)"), ("box", "package pickup"),
             ("dots", "rough (costs more)"), ("waves", "slippery floor")]
    for i, (sym, label) in enumerate(items):
        yy = 0.19 - i * 0.033
        axp.text(0.08, yy, {"house": "⌂", "star": "★", "triangle": "⚠",
                 "box": "■", "dots": "∴", "waves": "≈"}[sym],
                 fontsize=11, ha="center", va="center", color=PALETTE["ink"])
        axp.text(0.16, yy, label, fontsize=9.5, va="center", color=PALETTE["slate"])


def _render_bg_array(env, V, policy, hp, ppc=38):
    """Render the maze (values, arrows, icons) once to an RGBA image. The rollout
    video then shows this image and only animates the robot on top, so a long
    episode renders quickly instead of redrawing hundreds of cells every frame."""
    figb = plt.figure(figsize=(env.n_cols * ppc / 100.0, env.n_rows * ppc / 100.0),
                      dpi=100)
    axb = figb.add_axes([0, 0, 1, 1])
    _draw_layer(axb, env, V, policy, hp, "")
    axb.set_title("")
    axb.set_xlim(-0.5, env.n_cols - 0.5)
    axb.set_ylim(env.n_rows - 0.5, -0.5)
    axb.axis("off")
    figb.canvas.draw()
    w, h = figb.canvas.get_width_height()
    buf = np.asarray(figb.canvas.buffer_rgba()).reshape(h, w, 4).copy()
    plt.close(figb)
    return buf


def figure_rollout(env, V, policy, name="rollout.mp4", seed=0, fps=10, max_frames=700):
    """Animate one rollout with a live annotation panel (value, the four action
    values, the move taken, the reward and running return) and save it as an MP4
    video, one frame per step. Needs ffmpeg (the rl environment installs it); falls
    back to a GIF, then to a PNG filmstrip, so it never hard-fails."""
    from matplotlib import animation

    gamma = getattr(env, "gamma", 0.98)
    trace = rollout_trace(env, V, policy, gamma, seed=seed)
    sel = (sorted(set(np.linspace(0, len(trace) - 1, max_frames).astype(int)))
           if len(trace) > max_frames else list(range(len(trace))))

    # pre-render the maze background(s) as images (fast frames for long episodes)
    bg = {0: _render_bg_array(env, V, policy, 0)}
    bg[1] = _render_bg_array(env, V, policy, 1) if env.has_package_dim else bg[0]
    extent = [-0.5, env.n_cols - 0.5, env.n_rows - 0.5, -0.5]

    fig, (axm, axp) = plt.subplots(
        1, 2, figsize=(2.0 + 0.30 * (env.n_cols + 12), 1.4 + 0.30 * env.n_rows),
        dpi=90, gridspec_kw={"width_ratios": [env.n_cols, 12]})
    axm.axis("off")
    imbg = axm.imshow(bg[0], extent=extent, aspect="auto", zorder=0,
                      interpolation="antialiased")
    axm.set_xlim(-0.5, env.n_cols - 0.5)
    axm.set_ylim(env.n_rows - 0.5, -0.5)
    trail, = axm.plot([], [], "-", color=PALETTE["ink"], alpha=0.5, lw=2.2, zorder=3)
    axp.axis("off")
    axp.set_xlim(0, 1)
    axp.set_ylim(0, 1)
    _panel_legend(axp)
    keep = {id(imbg), id(trail)}
    cur = {"hp": 0}
    ARROW_CH = {"up": "↑", "down": "↓", "left": "←", "right": "→"}
    ink, slate = PALETTE["ink"], PALETTE["slate"]

    # Create the panel text objects ONCE and update them each frame (fast).
    t_step = axp.text(0.04, 0.90, "", fontsize=12, fontweight="bold", color=ink)
    t_carry = axp.text(0.55, 0.90, "", fontsize=11, color=ink)
    t_v = axp.text(0.04, 0.81, "", fontsize=11, color=ink)
    t_qh = axp.text(0.04, 0.72, "action values  q(s, a):", fontsize=11,
                    fontweight="bold", color=PALETTE["accent"])
    tq, ttag = [], []
    for k in range(len(env.actions)):
        yy = 0.65 - k * 0.058
        tq.append(axp.text(0.08, yy, "", fontsize=11, family="monospace", color=slate))
        ttag.append(axp.text(0.52, yy, "", fontsize=9.5, va="center", color=slate))
    t_mm = axp.text(0.04, 0.42, "", fontsize=9.5, color=PALETTE["bad"])
    t_rew = axp.text(0.04, 0.37, "", fontsize=11, color=ink)
    t_ret = axp.text(0.04, 0.33, "", fontsize=11, color=ink)
    t_slip = axp.text(0.04, 0.29, "", fontsize=10, fontweight="bold", color=PALETTE["orange"])
    t_term = axp.text(0.04, 0.80, "", fontsize=13, fontweight="bold")
    t_tret = axp.text(0.04, 0.70, "", fontsize=11, color=ink)
    normal = [t_v, t_qh, *tq, *ttag, t_mm, t_rew, t_ret, t_slip]

    def draw(i):
        info = trace[sel[i]]
        hp = info["hp"]
        if hp != cur["hp"]:
            imbg.set_data(bg[hp])
            cur["hp"] = hp
        for coll in (axm.patches, axm.lines, axm.texts):
            for art in list(coll):
                if id(art) not in keep:
                    art.remove()
        axm.set_title(f"step {sel[i]}    "
                      f"({'carrying package' if hp else 'no package'})",
                      fontsize=12, fontweight="bold")
        seg = [(e["c"], e["r"]) for e in trace[:sel[i] + 1] if e["hp"] == hp]
        if seg:
            xs, ys = zip(*seg)
            trail.set_data(xs, ys)
        _icon(axm, info["r"], info["c"], "robot")

        # info panel (update text in place)
        t_step.set_text(f"step {sel[i]}")
        t_carry.set_text("carrying: " + ("yes" if hp else "no"))
        term = info["term"]
        for obj in normal:
            obj.set_visible(not term)
        t_term.set_visible(term)
        t_tret.set_visible(term)
        if term:
            goal = env.tile(info["r"], info["c"]) == "G"
            t_term.set_text("DELIVERED" if goal else "hit a hazard")
            t_term.set_color(PALETTE["good"] if goal else PALETTE["bad"])
            t_tret.set_text(f"total return = {info['ret']:.1f}")
            return
        t_v.set_text(f"value of this cell   V = {info['Vs']:.1f}")
        for k, a in enumerate(env.actions):
            chosen = (a == info["action"])
            col = PALETTE["vermillion"] if chosen else slate
            tq[k].set_text(f"{ARROW_CH[a]} {a:<5} {info['qs'][a]:6.1f}")
            tq[k].set_color(col)
            tq[k].set_fontweight("bold" if chosen else "normal")
            tags = (["policy pick"] if chosen else []) + (["highest q"] if a == info["best"] else [])
            ttag[k].set_text("◄ " + ", ".join(tags) if tags else "")
            ttag[k].set_color(col)
        t_mm.set_text("policy did NOT pick the highest q (check your code)"
                      if info["action"] != info["best"] else "")
        t_rew.set_text(f"reward this step   {info['reward']:.0f}")
        t_ret.set_text(f"return so far      {info['ret']:.1f}")
        t_slip.set_text("SLIP! the floor slid the robot sideways" if info["slipped"] else "")

    anim = animation.FuncAnimation(fig, draw, frames=len(sel), interval=1000 // fps)
    out = FIGDIR / name
    if animation.FFMpegWriter.isAvailable():
        try:
            anim.save(out, writer=animation.FFMpegWriter(fps=fps, bitrate=2600))
            plt.close(fig)
            print("wrote", out)
            return out
        except Exception as exc:
            print("MP4 writer failed ({}); trying a GIF".format(exc))
    else:
        print("ffmpeg not found (install it in the rl env for MP4); writing a GIF")
    try:
        out = out.with_suffix(".gif")
        anim.save(out, writer=animation.PillowWriter(fps=fps))
        plt.close(fig)
        print("wrote", out)
        return out
    except Exception as exc:  # pragma: no cover
        plt.close(fig)
        print("Video writers unavailable ({}); saving a filmstrip".format(exc))
        return _filmstrip(env, V, policy, [t["s"] for t in trace], "rollout_filmstrip.png")


def _filmstrip(env, V, policy, path, name):
    picks = np.unique(np.linspace(0, len(path) - 1, min(6, len(path))).astype(int))
    fig, axes = plt.subplots(1, len(picks), figsize=(2.4 * len(picks), 2.6))
    if len(picks) == 1:
        axes = [axes]
    for ax, frame in zip(axes, picks):
        r, c, hp = env.decode(path[frame])
        _draw_layer(ax, env, V, policy, hp, f"step {frame}")
        ax.plot(c, r, "o", ms=12, color=PALETTE["vermillion"],
                markeredgecolor="white", markeredgewidth=1.2)
    return _save(fig, name)


set_style()
